# Generated by Django 3.0.3 on 2020-03-10 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facuty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('facuty_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.IntegerField()),
                ('food_name', models.CharField(max_length=50)),
                ('is_vegan', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('picture', models.ImageField(height_field=100, upload_to=None, verbose_name='', width_field=100)),
                ('open_time', models.DateField()),
                ('rating', models.IntegerField()),
                ('approve_by', models.CharField(max_length=50)),
                ('approve_date', models.DateField()),
                ('faculy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('is_staff', models.CharField(max_length=50)),
                ('is_superuser', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurentFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=10)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Food')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Restaurant')),
            ],
        ),
    ]
